language: node_js
node_js:
  - 'node'

script:
  yarn test

after_success:
  yarn coverage

services:
  - postgresql

before_script:
  - psql -c 'drop database test1;' -U postgres
  - psql -c 'create database test1;' -U postgres